// Mocks generated by Mockito 5.4.4 from annotations
// in pokedex_app/test/domain/get_pokemon_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_app/data/models/pokemon_detail_model.dart' as _i2;
import 'package:pokedex_app/data/models/pokemon_model.dart' as _i5;
import 'package:pokedex_app/data/repositories/pokemon_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonDetailModel_0 extends _i1.SmartFake
    implements _i2.PokemonDetailModel {
  _FakePokemonDetailModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i3.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PokemonModel>> getPokemons(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [
            limit,
            offset,
          ],
        ),
        returnValue:
            _i4.Future<List<_i5.PokemonModel>>.value(<_i5.PokemonModel>[]),
      ) as _i4.Future<List<_i5.PokemonModel>>);

  @override
  _i4.Future<_i2.PokemonDetailModel> getPokemonDetails(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetails,
          [url],
        ),
        returnValue:
            _i4.Future<_i2.PokemonDetailModel>.value(_FakePokemonDetailModel_0(
          this,
          Invocation.method(
            #getPokemonDetails,
            [url],
          ),
        )),
      ) as _i4.Future<_i2.PokemonDetailModel>);
}
