// Mocks generated by Mockito 5.4.4 from annotations
// in pokedex_app/test/domain/get_pokemon_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_app/data/models/pokemon_evolution_model.dart' as _i5;
import 'package:pokedex_app/data/models/pokemon_info_model.dart' as _i3;
import 'package:pokedex_app/data/models/pokemon_model.dart' as _i8;
import 'package:pokedex_app/data/models/pokemon_summary_model.dart' as _i2;
import 'package:pokedex_app/data/models/pokemon_type_info_model.dart' as _i4;
import 'package:pokedex_app/data/repositories/pokemon_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonSummaryModel_0 extends _i1.SmartFake
    implements _i2.PokemonSummaryModel {
  _FakePokemonSummaryModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonInfoModel_1 extends _i1.SmartFake
    implements _i3.PokemonInfoModel {
  _FakePokemonInfoModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonTypeInfoModel_2 extends _i1.SmartFake
    implements _i4.PokemonTypeInfoModel {
  _FakePokemonTypeInfoModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonEvolutionModel_3 extends _i1.SmartFake
    implements _i5.PokemonEvolutionModel {
  _FakePokemonEvolutionModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i6.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i8.PokemonModel>> getPokemons(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [
            limit,
            offset,
          ],
        ),
        returnValue:
            _i7.Future<List<_i8.PokemonModel>>.value(<_i8.PokemonModel>[]),
      ) as _i7.Future<List<_i8.PokemonModel>>);

  @override
  _i7.Future<_i2.PokemonSummaryModel> getPokemonSummary(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonSummary,
          [url],
        ),
        returnValue: _i7.Future<_i2.PokemonSummaryModel>.value(
            _FakePokemonSummaryModel_0(
          this,
          Invocation.method(
            #getPokemonSummary,
            [url],
          ),
        )),
      ) as _i7.Future<_i2.PokemonSummaryModel>);

  @override
  _i7.Future<_i3.PokemonInfoModel> getPokemonInfo(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonInfo,
          [url],
        ),
        returnValue:
            _i7.Future<_i3.PokemonInfoModel>.value(_FakePokemonInfoModel_1(
          this,
          Invocation.method(
            #getPokemonInfo,
            [url],
          ),
        )),
      ) as _i7.Future<_i3.PokemonInfoModel>);

  @override
  _i7.Future<_i4.PokemonTypeInfoModel> getPokemonTypeInfo(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonTypeInfo,
          [url],
        ),
        returnValue: _i7.Future<_i4.PokemonTypeInfoModel>.value(
            _FakePokemonTypeInfoModel_2(
          this,
          Invocation.method(
            #getPokemonTypeInfo,
            [url],
          ),
        )),
      ) as _i7.Future<_i4.PokemonTypeInfoModel>);

  @override
  _i7.Future<_i5.PokemonEvolutionModel> getPokemonEvolution(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonEvolution,
          [url],
        ),
        returnValue: _i7.Future<_i5.PokemonEvolutionModel>.value(
            _FakePokemonEvolutionModel_3(
          this,
          Invocation.method(
            #getPokemonEvolution,
            [url],
          ),
        )),
      ) as _i7.Future<_i5.PokemonEvolutionModel>);
}
